### ISSUE TITLE
Work with local files

### ISSUE THREAD

**Issue by RomanGrankin** [schmijos/html-table-parser-python3#10]
Please advise how to work with pre-downloaded files (ie index.html) instead of getting it through request. Thank you!

**Comment by davidov541** [comment]
@RomanGrankin - You should be able to just read the file into a string, and then pass this into feed. You can take a look at the test_singleTable function in the test/test_parser.py file for an example. We pull a string from self.getTestInput, and then pass it directly into HTMLTableParser.feed().

If this is what you are looking for, let me know and I can make a point of adding an example into the documentation for this.

**Comment by RomanGrankin** [comment]
@davidov541 Thank you very much for explaining! That is exactly what I was looking for :)

**Comment by abubelinha** [comment]
> I can make a point of adding an example into the documentation for this

@davidov541 I think such examples would be useful.
I am interested in two use cases:
- finding and parsing tables in a local file
- not finding anything: just parsing a "`<table class='myclass'>...</table>`" string which I already have

One question: is this library case sensitive or would it parse/find strings like "`<tAbLe cLASs='myclass'> ... </TAble>`"?

Thanks!
@abubelinha
