### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by DmitrySobolevone** [schmijos/html-table-parser-python3#6]
I got information from the site https://ksoe.com.ua/disconnection/planned/
He extracts all the blocks, is it possible to extract certain blocks, interests <td>Каховський РЕЗ і ЕМ</td>

Is it possible to filter information and get it with such a name?

**Comment by DmitrySobolevone** [comment]
Or filter blocks by date, which would give out blocks of today's date.

**Comment by schmijos** [comment]
Hi @DmitrySobolevone 

There's no such feature here natively. You could edit the parsed table depending on data you encounter in here: https://github.com/schmijos/html-table-parser-python3/blob/master/html_table_parser/parser.py#L50

The easiest would be to not add data with `self._current_cell.append(data.strip())` if you're not interested into it (or leave a sentinel) and then afterwards clean up the whole table.
